usgs/groundfailure

groundfailure/conf.py
groundfailure/logisticmodel.py
groundfailure/makemaps.py
groundfailure/newmark.py
groundfailure/savelayers.py
groundfailure/testmodels.py

Still need to update lsprocess to python 3 in order for testmodels.py to work

Updated to Python 3, will no longer work with Python 2.7

---

README.md
groundfailure/logisticmodel.py
groundfailure/makemaps.py

Logistic model updated to be more consistent with other models, to propagate metadata, and implemented slope thresholds. Numerous changes to config file (reflected in README) so now all models seem to work except the updated landslide model. Still waiting on input files for that one. And still need to validate all models, so far they were just validated visually against results in papers.

Addoriginal

---

groundfailure/logisticmodel.py
groundfailure/makemaps.py
groundfailure/newmark.py

Not very far along, but added uncertainty to checkterm function and reads in uncertainty into logistic model class.  Still not entirely sure how to add uncertainty overall to the class.

Preliminary addition of uncert to logistic model.

---

LICENSE
README.md
defaultconfigfiles/models/zhu_2015.ini
defaultconfigfiles/models/zhu_2016_coastal.ini
defaultconfigfiles/models/zhu_2016_general.ini
groundfailure/logisticmodel.py
setup_env.sh

* License/disclaimer stuff because software has not "been approved".
* Add branca to dependencies
* Added 'pgamin' and 'vs30max' to config file (not required)
* Added [[coverage]] to ini file (not required)
* Added config to LogisticModel class

Updates to Zhu model

---

defaultconfigfiles/models/holzer_liq_cal.ini
gfail
groundfailure/hazus.py
groundfailure/holzer.py

Added Holzer module. Removed local data paths. Renamed Hazus module since it can be used outside of California.

Add Holzer model

---

groundfailure/kritikos.py

Some minor changes to Kritikos as well as adding additional comments so that it is easier to understand.

Kritikos commenting

---

.gitignore
defaultconfigfiles/models/godt_2008.ini
defaultconfigfiles/models/jessee_2017.ini
defaultconfigfiles/models/nowicki_2014_global.ini
defaultconfigfiles/models/nowicki_2015.ini
defaultconfigfiles/models/zhu_2017_coastal.ini
defaultconfigfiles/models/zhu_2017_general.ini
gfail
groundfailure/logisticmodel.py
groundfailure/makemaps.py
groundfailure/newmark.py

Fixed mix of nan and zero probabilities in areas outside thresholds in logistic model
Added slope threshold to Godt model to address issue where when pga is super high (in this case >4g), the thresholds cause probabilities of 1 everywhere in high pga zone.
Reduced density of cities
Made zero and nan areas clear in interactive plots
Added option to add words to end of filenames to differentiate different model runs in gfail
Fixed bug with scalebar for some plot types

Fixed a lot of little bugs revealed by Mexico earthquake

---

groundfailure/gdalfuncs.py
groundfailure/hazus.py
groundfailure/holzer.py
groundfailure/logisticmodel.py
groundfailure/makemaps.py
groundfailure/newmark.py

Also added documentation to a few functions that didn't have any yet.

fixed up documentation to reduce formatting weirdness in sphinx

---

defaultconfigfiles/models/jessee_2017.ini
groundfailure/assessmodels.py
groundfailure/logisticmodel.py
groundfailure/testmodels.py
setup_env.sh
tests/gfail_test.py

Added normalized cross correlation
Added shaking threshold option to aggregate hazard calculation
Figured out the best projection to use for area calculations
Fixed alignment problems in outputs from convert2Coverage
Fixed problem with travis failing - it was because I was installing folium from the master branch of the github repo and someone changed something - I modified it to load a released version

Fixed up testmodels (now called assessmodels)

---

groundfailure/assessmodels.py

This is meant for looping over probability thresholds and getting the total area exceeding that probability threshold. Might be useful. Might not.

Added hagg2--an alternative definition of hagg to try out

---

defaultconfigfiles/models/jessee_2017.ini

Now cites her dissertation rather than the submitted paper.

Updated citation in jessee config file

---

bin/autogf
bin/gfail
environment.yml
environment_linux.yml
environment_osx.yml
gfail/pdl.py
install.sh
tests/autogf_test.py
tests/gfail_test.py

And updated to install script to adjust to users operating system.

Addition of new format needed for ShakeCast

---

bin/autogf
bin/gfail
defaultconfigfiles/autoconfig.ini
environment_linux.yml
gfail/webpage.py
tests/gfail_test.py

Also added more columns to the sqlite database that are used to determine when a change is "significant"
Added logic to ensure that new versions of events that were already run but dropped below the thresholds are still run

Added logic to avoid sending emails for minor changes

---

bin/autogf
bin/gfail
environment.yml
environment_linux.yml
environment_osx.yml
gfail/logisticmodel.py
gfail/pdl.py
gfail/webpage.py
install.sh

Added simple summary that explains the models to all results. Also added a note about finite faults for larger events (M>6.5) with point sources. Now using libcomcat to find the finite fault if not specified and to get the right shakemap url. Also fixed some other minor bugs.

Added general model summary to webpage

---

gfail/webpage.py

This is just some minor tweaks that I'm using to generate table of summary statistics. In particular, we needed smaller probability thresholds for the Jessee model, which has much lower probabilities than before. Also the degwin change is because at least one event was not associating in comcat because of the differences in the epicenter location.

Increase degwin to 0.3; added extra probthresh values

---

bin/gfail_transfer
gfail/pdl.py
gfail/webpage.py
tests/autogf_test.py
tests/gfail_test.py

This modifies the PDL properties and the files transferred based on feedback from the web team.

Updates based on meeting with web team

---

gfail/pdl.py

Fixed extent error noted by both @kallstadt-usgs and @ehunter-usgs.

Fixed product extent vs landslide extent error

---

bin/callgf
gfail/gfailrun.py
gfail/utilities.py
gfail/webpage.py

- Added the new more rigorous method for detecting if the shakemap used a point rupture
- Put a copy of the shakemap grid.xml file into the output directory
- Slight change to logging statements

Detect rupture fix and copy grid.xml

---

gfail/gfailrun.py
gfail/webpage.py

Added web mercator projection to png creation and added hdf5 files to output file list in gfailrun.py

Projection

---

gfail/pdl.py
gfail/webpage.py
install.sh

I hope this PR fixes the install issues reported in #194. Also, I've added the summary alert level (max of population and hazard alerts) as product properties.

Install script and summary alerts

---

bin/callgf
defaultconfigfiles/models/jessee_2017.ini
gfail/makemaps.py
gfail/pdl.py
gfail/webpage.py

Updated callgf to better deal with events that don't run, cleans up excess folders and avoids rerunning events. Added shakemap_version to database.
Updated Nowicki Jessee citations throughout to reflect the paper in press.
Changed organization of downloads section to describe which models are preferred and which type each model is.

Further updates to callgf and pdl.py

---

gfail/pdl.py

Closes #216 (assuming this works, hard to test until it is merged).

Added pdl key path

---

.travis.yml
environment.yml
install.sh

Need to remove packages that are not in conda forge. I think the only one we actually need that is not in conda forge is configobj so I'm installing it with pip. This installs and passes tests on OSX. When I do it in linux I get bizarre results and it fails. But when Mike does it with his account on a linux machine with the same commands, it seems to work somehow so I suppose there's a chance this will work on Travis.

Trying to fix install

---

bin/callgf
gfail/pdl.py
gfail/transfer.py
tests/gfail_test.py

Added version number to product properties

---

bin/callgf
gfail/gfailrun.py
gfail/logisticmodel.py
gfail/pdl.py
gfail/stats.py
gfail/utilities.py
gfail/webpage.py
tests/logisticmodel_test.py
tests/stats_test.py

Also
-added option to specify source and shakemap verison when running callgf from command line
-added many new fields to database (will need to modify existing file before running on near-real-time machine)
-outputs p and q, the shapefactors for the beta distribution for the aggregate statistics and the upper bound of the beta distribution - all are needed to construct the pdf of the distribution
-new product properties for pdl to reflect uncertainty
-fixed minor bug with viewdb

Added uncertainty capabilities for preferred models and alert levels

---

.gitignore
gfail/gfailrun.py
gfail/pdl.py

Added lossless compression for for gtif files, removed flt files, removed hdf files.

Reduce file size of product in comcat

---

bin/callgf
gfail/gfailrun.py
gfail/utilities.py
tests/callgf_test.py

This code should repair the issue with old ShakeMap's inadvertently being loaded in as the "preferred" one. ALso some adjustments to plotting options and a fix to the stop file functionality (plus tests).

Fix libcomcat issue and some plotting functions

---

gfail/gfailrun.py
gfail/utilities.py

Also fixed small bug in viewdb

fixed bug in bounds adjustment for unavailable input layers

---

defaultconfigfiles/models/zhu_2017_coastal.ini
gfail/gfailrun.py
gfail/stats.py
gfail/webpage.py

- Fixes one bug in which values were being inadvertently changed during kmz creation that was slightly affecting uncertainty estimates.
- Rearranged the uncertainty estimates so they are done in the stats module instead of in the webpage module.
- Adds adaptive method for estimating sill and range, if the range isn't found at the first maximum range allowed, then the maximum range that can be searched is expanded. If still finds nothing (common when there are few non-zero values), then it uses the maximum uncertainty estimate (based on sum of std values).
- Also updated coastal liquefaction model config file with changes

Fixes to uncertainty estimates

---

azure-pipelines.yml
bin/callgf
install.sh
tests/callgf_test.py

- Fixed Azure build failures due to conda not being found mid-script; I still don't understand how this happens when it was successfully found and run earlier in the script
-  Fixed bug in writing to sqlite db that was created when I removed the code for checking if the extent spans the 180 discontinuity; this is where the `note` variable was initialized and so subsequent references to it created errors.

Fix install script on azure and sql bug

---

gfail/models/jessee_2018.py

Hello,
Here a commit to solve this issue #358

fstring correction
